# ================================
#        Config
# ================================
# Database Configuration
# Allowed Database Types
# - H2
# - FLAT
# - MYSQL
# - REDIS
host: localhost
database: pythontest
user_name: root
password: ''
port: 3306
use_ssl: false
db_type: MARIADB